# Лабораторная работа 1
Pandas

Выполнил: 6133, Борисов Дмитрий Сергеевич

In [1]:
import pandas as pd
import numpy as np

### 1 Считать в pandas DataFrame любой источник данных:  CSV, JSON, Excel-файл, HTML-таблицу, встроенный датасет sklearn. Опишите ваши данные, что обозначает каждый столбец, какого типа (категориальный, вещественный, целочисленный, бинарный) данный столбец, при необходимости для категориальных в том числе бинарных признаков привести расшифровку их значений. В общем, проведите "визуальный" анализ ваших данных.

Этот набор данных содержит субтитры из более чем 91 различных ютуберов, начиная от самых разных категорий. В настоящее время набор данных содержит 2515 уникальных видеороликов и их субтитров. В наборе данных 11 столбцов:

**Id** - Unique ID for the video. (ex, dQw4w9WgXcQ)

**Channel** - Name of the YouTube channel

**Subscribers** - How many subscribers did the channel have while creating the dataset

**Title** - Title of the video

**CC** - Did the video have manual subtitles? (0 means that the Transcript is auto-generated, and may be less reliable)

**URL** - URL of the video

**Released** - When the video was released

**Views** - How many views did the video have during the collection of this dataset

**Category** - Category of the channel

**Transcript** - Subtitle of the video

**Lenght** - Length pf the video

In [2]:
data = pd.read_csv("data/data.csv")

### 2 Выполните с датафреймом следующие операции (многие операции можно совершить не одним способом, используйте все известные вам способы, поищите/придумайте новые способы) :

#### 2.1 вывод таблицы

In [3]:
data

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51
3,JiEO6F8i0eU,Parks and Recreation,282K subscribers,Ron Swanson: The Papa of Pawnee | Parks and Re...,0,https://www.youtube.com/watch?v=JiEO6F8i0eU,3 years ago,2.3M views,"Entertainment,Comedy",April where have you been over two phone calls...,10:06
4,1T4XMNN4bNM,Vsauce,17.4M subscribers,What's The Most Dangerous Place on Earth?,1,https://www.youtube.com/watch?v=1T4XMNN4bNM,9 years ago,21M views,Science,"Hey, Vsauce. Michael here. 93% of all the\r\nh...",9:29
...,...,...,...,...,...,...,...,...,...,...,...
2510,DonD68byO0o,Parks and Recreation,282K subscribers,Best of Andy Dwyer | Parks and Recreation,0,https://www.youtube.com/watch?v=DonD68byO0o,3 years ago,2.8M views,"Entertainment,Comedy",oh I guess while you get your medicine I'll ju...,10:05
2511,iaEcZW0eyEg,Hell's Kitchen,1.5M subscribers,Gordon Ramsay's Most Savage Moments | Hell's K...,0,https://www.youtube.com/watch?v=iaEcZW0eyEg,11 months ago,6.4M views,Food,southern girl keisha hopes to get the women on...,8:33
2512,sW9npZVpiMI,Joma Tech,1.59M subscribers,why you NEED math for programming,0,https://www.youtube.com/watch?v=sW9npZVpiMI,NaN,4.5M views,"Tech,Comedy",[Music] okay [Music] jesus nope not jesus it's...,5:03
2513,yl3MiR7XXAM,jacksepticeye,28M subscribers,Happy Wheels - Part 1 | THIS GAME IS MY BITCH,1,https://www.youtube.com/watch?v=yl3MiR7XXAM,8 years ago,20M views,VideoGames,"Top o' the mornin' to ya, laddies! My name i...",13:32
2514,dJfSS0ZXYdo,Top Gear,8.24M subscribers,The Smallest Car in the World at the BBC - Top...,1,https://www.youtube.com/watch?v=dJfSS0ZXYdo,13 years ago,26M views,"Automobile,Comedy","And there's more, because as the country\r\nbe...",8:58

#### 2.2 вывод первых n элементов таблицы

In [4]:
n = 6
data.head(n)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51
3,JiEO6F8i0eU,Parks and Recreation,282K subscribers,Ron Swanson: The Papa of Pawnee | Parks and Re...,0,https://www.youtube.com/watch?v=JiEO6F8i0eU,3 years ago,2.3M views,"Entertainment,Comedy",April where have you been over two phone calls...,10:06
4,1T4XMNN4bNM,Vsauce,17.4M subscribers,What's The Most Dangerous Place on Earth?,1,https://www.youtube.com/watch?v=1T4XMNN4bNM,9 years ago,21M views,Science,"Hey, Vsauce. Michael here. 93% of all the\r\nh...",9:29
5,0ZWGeidvrJw,Doctor Who,1.59M subscribers,The Doctor Defeats the Abzorbaloff | Love and ...,1,https://www.youtube.com/watch?v=0ZWGeidvrJw,7 years ago,8.5M views,Entertainment,"Oh, what's the matter?\r\nHave you given up so...",4:20

#### 2.3 вывод последних n элементов таблицы

In [5]:
n = 4
data.tail(n)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
2511,iaEcZW0eyEg,Hell's Kitchen,1.5M subscribers,Gordon Ramsay's Most Savage Moments | Hell's K...,0,https://www.youtube.com/watch?v=iaEcZW0eyEg,11 months ago,6.4M views,Food,southern girl keisha hopes to get the women on...,8:33
2512,sW9npZVpiMI,Joma Tech,1.59M subscribers,why you NEED math for programming,0,https://www.youtube.com/watch?v=sW9npZVpiMI,NaN,4.5M views,"Tech,Comedy",[Music] okay [Music] jesus nope not jesus it's...,5:03
2513,yl3MiR7XXAM,jacksepticeye,28M subscribers,Happy Wheels - Part 1 | THIS GAME IS MY BITCH,1,https://www.youtube.com/watch?v=yl3MiR7XXAM,8 years ago,20M views,VideoGames,"Top o' the mornin' to ya, laddies! My name i...",13:32
2514,dJfSS0ZXYdo,Top Gear,8.24M subscribers,The Smallest Car in the World at the BBC - Top...,1,https://www.youtube.com/watch?v=dJfSS0ZXYdo,13 years ago,26M views,"Automobile,Comedy","And there's more, because as the country\r\nbe...",8:58

#### 2.4 .describe()

In [6]:
data.describe(include='all')

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
count,2515,2515,2515,2515,2515.000000,2515,2098,2515,2515,2515,2515
unique,2515,91,88,2513,NaN,2515,29,400,22,2515,1321
top,FozCkl1xj-w,The Daily Show with Trevor Noah,3.35M subscribers,Nissan GTR Power Lap | The Stig | Top Gear,NaN,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,10M views,Science,the Joe Rogan experience well how about the ot...,10:03
freq,1,30,58,2,NaN,1,521,104,323,1,10
mean,NaN,NaN,NaN,NaN,0.450895,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,0.497682,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2515 entries, 0 to 2514
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           2515 non-null   object
 1   Channel      2515 non-null   object
 2   Subscribers  2515 non-null   object
 3   Title        2515 non-null   object
 4   CC           2515 non-null   int64
 5   URL          2515 non-null   object
 6   Released     2098 non-null   object
 7   Views        2515 non-null   object
 8   Category     2515 non-null   object
 9   Transcript   2515 non-null   object
 10  Length       2515 non-null   object
dtypes: int64(1), object(10)
memory usage: 216.3+ KB

#### 2.5 считывание значения конкретной ячейки (с конкретным индексом из конкретной колонки)  всеми известными вам способами

In [8]:
data.Channel[3]

'Parks and Recreation'

In [9]:
data['Channel'][3]

'Parks and Recreation'

In [10]:
data.iloc[3, 1]

'Parks and Recreation'

In [11]:
data.loc[3]['Channel']

'Parks and Recreation'

In [12]:
data.at[3, 'Channel']

'Parks and Recreation'

In [13]:
data.iat[3, 1]

'Parks and Recreation'

#### 2.6 фильтрация строк по диапазону индекса

In [14]:
start = 1
end = 3

In [15]:
data[start:end]

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51

In [16]:
data.loc[start:end]

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51
3,JiEO6F8i0eU,Parks and Recreation,282K subscribers,Ron Swanson: The Papa of Pawnee | Parks and Re...,0,https://www.youtube.com/watch?v=JiEO6F8i0eU,3 years ago,2.3M views,"Entertainment,Comedy",April where have you been over two phone calls...,10:06

In [17]:
data.iloc[start:end]

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51

#### 2.7 фильтрация набора данных по какому-либо условию

In [18]:
data[data.CC == 1]

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
4,1T4XMNN4bNM,Vsauce,17.4M subscribers,What's The Most Dangerous Place on Earth?,1,https://www.youtube.com/watch?v=1T4XMNN4bNM,9 years ago,21M views,Science,"Hey, Vsauce. Michael here. 93% of all the\r\nh...",9:29
5,0ZWGeidvrJw,Doctor Who,1.59M subscribers,The Doctor Defeats the Abzorbaloff | Love and ...,1,https://www.youtube.com/watch?v=0ZWGeidvrJw,7 years ago,8.5M views,Entertainment,"Oh, what's the matter?\r\nHave you given up so...",4:20
6,YiEj9mrqTN0,A&E,7.93M subscribers,Live PD: Most Viewed Moments from Walton Count...,1,https://www.youtube.com/watch?v=YiEj9mrqTN0,2 years ago,14M views,News,[music playing] We'll be on Laverne Street. It...,20:54
9,VT128ElBWkM,Incognito Mode,1.62M subscribers,The Roswell Incident,1,https://www.youtube.com/watch?v=VT128ElBWkM,4 years ago,2.2M views,"Blog,Comedy",This evening we're going to explore the story....,4:20
...,...,...,...,...,...,...,...,...,...,...,...
2505,2nYF46P7B2c,ChrisFix,8.69M subscribers,How to Remove Scratches from Car PERMANENTLY (...,1,https://www.youtube.com/watch?v=2nYF46P7B2c,5 years ago,16M views,Automobile,"Hey guys, Chris Fix here. Today, I'm going to ...",11:58
2506,S32y9aYEzzo,Mark Rober,21.1M subscribers,How to measure HOW MUCH PEE IS IN YOUR POOL,1,https://www.youtube.com/watch?v=S32y9aYEzzo,4 years ago,33M views,Science,Now that summer is winding down and you've alr...,10:30
2508,pwIhn9Ljeqo,LEMMiNO,4.68M subscribers,Top 10 Facts - Grand Theft Auto,1,https://www.youtube.com/watch?v=pwIhn9Ljeqo,7 years ago,5.3M views,Informative,It started as a simple top-down Cops-And-Robbe...,6:30
2513,yl3MiR7XXAM,jacksepticeye,28M subscribers,Happy Wheels - Part 1 | THIS GAME IS MY BITCH,1,https://www.youtube.com/watch?v=yl3MiR7XXAM,8 years ago,20M views,VideoGames,"Top o' the mornin' to ya, laddies! My name i...",13:32
2514,dJfSS0ZXYdo,Top Gear,8.24M subscribers,The Smallest Car in the World at the BBC - Top...,1,https://www.youtube.com/watch?v=dJfSS0ZXYdo,13 years ago,26M views,"Automobile,Comedy","And there's more, because as the country\r\nbe...",8:58

#### 2.8. работа с пропущенными значениями (если они есть): удаление строк с пропущенными значениями, заполнение пропущенных значений средним значением по колонке. Если пропущенных значений нет — намеренно их "генерируете", прибивая какие-то куски данных в np.nan

In [19]:
df = data.copy()
df.shape

(2515, 11)

In [20]:
print("Количество строк со значением Nan: ", df[df.Released.isna()].shape[0])

Количество строк со значением Nan:  417

In [21]:
df = df[df.Released.notna()]
df.shape

(2098, 11)

In [22]:
df = data.copy()
df = df.dropna()
df.shape

(2098, 11)

In [23]:
df = data.copy()
df.replace(np.NAN, 'Unknown').head(3)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,Unknown,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51

In [24]:
df = data.copy()
df.fillna('Unknown').head(3)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,Unknown,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51

#### 2.9. создание нового поля вычисленного на основе значений других полей:

##### 2.9.1 через выражение на базе имеющихся колонок,

In [25]:
data["CC bool"] = data["CC"] == 1

##### 2.9.2 через DataFrame.apply

In [26]:
def get_seconds(row):
    time_split = row['Length'].split(':')
    return int(time_split[0]) * 60 + int(time_split[1])
    
data["Seconds"] = data.apply(get_seconds, axis=1)

##### 2.9.3 через Series.apply

In [28]:
data["Minutes"] =  data["Seconds"].apply(lambda s: s / 60)

In [29]:
data.head(5)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length,CC bool,Seconds,Minutes
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32,False,812,13.533333
1,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26,True,1466,24.433333
2,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51,False,471,7.850000
3,JiEO6F8i0eU,Parks and Recreation,282K subscribers,Ron Swanson: The Papa of Pawnee | Parks and Re...,0,https://www.youtube.com/watch?v=JiEO6F8i0eU,3 years ago,2.3M views,"Entertainment,Comedy",April where have you been over two phone calls...,10:06,False,606,10.100000
4,1T4XMNN4bNM,Vsauce,17.4M subscribers,What's The Most Dangerous Place on Earth?,1,https://www.youtube.com/watch?v=1T4XMNN4bNM,9 years ago,21M views,Science,"Hey, Vsauce. Michael here. 93% of all the\r\nh...",9:29,True,569,9.483333


#### 2.10 сортировка по какому-либо из полей

In [30]:
data.sort_values( by = 'CC' )

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length,CC bool,Seconds,Minutes
0,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32,False,812,13.533333
1088,J1ugR-VVE1I,Sky News,3.98M subscribers,Mosul's snatch squads,0,https://www.youtube.com/watch?v=J1ugR-VVE1I,4 years ago,6.7M views,News,it is a nervous drive through unfamiliar terri...,4:03,False,243,4.050000
1087,obng-x8oAk4,CDawgVA,2.6M subscribers,I Try EVERY Japanese Alcohol Ft. @Abroad in Japan,0,https://www.youtube.com/watch?v=obng-x8oAk4,10 months ago,2.2M views,Blog,so yes this is a very concerning looking video...,31:45,False,1905,31.750000
2021,kNZV3Bry5UU,Car Throttle,3.08M subscribers,Stupid Things People Say When Selling A Car,0,https://www.youtube.com/watch?v=kNZV3Bry5UU,3 years ago,3.3M views,Automobile,[Music] German car [Music] oh wait I'm done fo...,14:57,False,897,14.950000
2022,cvLbjQ11GAM,Hell's Kitchen,1.5M subscribers,The Best Moments Of Hell's Kitchen Season 14,0,https://www.youtube.com/watch?v=cvLbjQ11GAM,2 years ago,6.9M views,Food,Millie Millie yes and you from wherever Philly...,15:03,False,903,15.050000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1141,4H5--Qy3h9Q,The Try Guys,7.7M subscribers,Keith Eats Everything At KFC,1,https://www.youtube.com/watch?v=4H5--Qy3h9Q,3 years ago,17M views,"Entertainment,Blog","In 1930, in North Corbin, Kentucky, one \r\n ...",18:27,True,1107,18.450000
1136,wCrtk-pyP0I,Veritasium,11.4M subscribers,Microwaving Grapes Makes Plasma,1,https://www.youtube.com/watch?v=wCrtk-pyP0I,2 years ago,17M views,Science,almost eight years ago when this channel\r\nwa...,8:16,True,496,8.266667
1135,ADb60W8jTsM,Insider News,216K subscribers,Inside Poland's 'LGBT-Free' Zones | Insider Docs,1,https://www.youtube.com/watch?v=ADb60W8jTsM,3 months ago,906K views,News,Narrator: Poland has been dubbed\r\nthe worst ...,12:53,True,773,12.883333
1191,oHLMla-75QA,The Infographics Show,11.3M subscribers,What To ACTUALLY Do If You Are Buried Alive,1,https://www.youtube.com/watch?v=oHLMla-75QA,2 years ago,9M views,Informative,You wake up one day and feel a bit groggy. The...,7:02,True,422,7.033333
2514,dJfSS0ZXYdo,Top Gear,8.24M subscribers,The Smallest Car in the World at the BBC - Top...,1,https://www.youtube.com/watch?v=dJfSS0ZXYdo,13 years ago,26M views,"Automobile,Comedy","And there's more, because as the country\r\nbe...",8:58,True,538,8.966667

#### 2.11 вычислить несколько статистик по колонкам (используйте встроенные агрегатные функции — любые на выбор)

In [32]:
print(data['Released'].count(), data['Seconds'].min(), data['Seconds'].max(), data['Seconds'].sum())

2098 16 3563 1878192

#### 2.12 .value_counts()

In [33]:
data.loc[:, data.columns != 'Transcript'].value_counts()

Id           Channel                 Subscribers        Title                                                                                      CC  URL                                          Released      Views       Category              Length  CC bool  Seconds  Minutes
-28pKoQdMl8  ElectroBOOM             4.97M subscribers  Failed to Fix Your Cell Phone? Make a Robot                                                1   https://www.youtube.com/watch?v=-28pKoQdMl8  5 years ago   4.3M views  Science               6:07    True     367      6.116667     1
fXUsRIcwtSo  The Graham Norton Show  4.08M subscribers  Jodie Foster Has Never Spoken To Anthony Hopkins - The Graham Norton Show                  0   https://www.youtube.com/watch?v=fXUsRIcwtSo  5 years ago   12M views   Entertainment,Comedy  2:03    False    123      2.050000     1
fVDOB9mby_w  Team Coco               8.41M subscribers  Conan Takes Jordan Schlansky Coffee Tasting | CONAN on TBS                                 0   https://www.youtube.com/watch?v=fVDOB9mby_w  7 years ago   19M views   Comedy,Entertainment  8:29    False    509      8.483333     1
fTgm36y884c  Epicurious              4.01M subscribers  How To Cut Every Cheese | Method Mastery | Epicurious                                      1   https://www.youtube.com/watch?v=fTgm36y884c  9 months ago  10M views   Food                  42:03   True     2523     42.050000    1
fNk_zzaMoSs  3Blue1Brown             4.28M subscribers  Vectors | Chapter 1, Essence of linear algebra                                             1   https://www.youtube.com/watch?v=fNk_zzaMoSs  5 years ago   5.2M views  Science               9:52    True     592      9.866667     1
                                                                                                                                                                                                                                                                                          ..
Kpnd4OVf7oo  Linus Tech Tips         14.3M subscribers  The World's Ugliest Keyboard                                                               0   https://www.youtube.com/watch?v=Kpnd4OVf7oo  5 years ago   9.8M views  Tech                  9:37    False    577      9.616667     1
Kou7ur5xt_4  Mark Rober              21.1M subscribers  World's Largest Elephant Toothpaste Experiment                                             0   https://www.youtube.com/watch?v=Kou7ur5xt_4  2 years ago   80M views   Science               10:33   False    633      10.550000    1
KnMKCHqXLow  Vox                     10.3M subscribers  It's not you. Claw machines are rigged.                                                    1   https://www.youtube.com/watch?v=KnMKCHqXLow  6 years ago   9.7M views  Informative           3:51    True     231      3.850000     1
Kjp3PTeXBew  The Graham Norton Show  4.08M subscribers  Jennifer Lawrence Shocked By Eddie Redmayne's Early Model Photos - The Graham Norton Show  1   https://www.youtube.com/watch?v=Kjp3PTeXBew  6 years ago   27M views   Entertainment,Comedy  4:12    True     252      4.200000     1
zyVZ73CBR7Y  Coder Coder             306K subscribers   How to deploy your website for free                                                        1   https://www.youtube.com/watch?v=zyVZ73CBR7Y  4 months ago  55K views   Tech,Informative      0:53    True     53       0.883333     1
Length: 2098, dtype: int64

#### 2.13 Вывод уникальных значений колонки через .unique()

In [34]:
data['Category'].unique()

array(['Blog', 'Food', 'Entertainment,Comedy', 'Science', 'Entertainment',
       'News', 'VideoGames', 'Blog,Comedy', 'Comedy,Entertainment',
       'Blog,Science', 'Tech', 'Tech,Comedy', 'Comedy,Informative',
       'Automobile,Comedy', 'Informative', 'Tech,News', 'Automobile',
       'Tech,Informative', 'Food,Entertainment', 'Blog,Entertainment',
       'Entertainment,Blog', 'Comedy'], dtype=object)

#### 2.14 Удалите текущий индекс и создайте новый индекс на базе новой колонки, которая для этого лучше всего подходит

In [35]:
df = data.copy()
df.index = data['Id']
df.head(3)

,Id,Channel,Subscribers,Title,CC,URL,Released,Views,Category,Transcript,Length,CC bool,Seconds,Minutes
Id,,,,,,,,,,,,,,
FozCkl1xj-w,FozCkl1xj-w,JRE Clips,6.28M subscribers,Former CIA Agent Breaks Down Jeffrey Epstein Case,0,https://www.youtube.com/watch?v=FozCkl1xj-w,2 years ago,7.9M views,Blog,the Joe Rogan experience well how about the ot...,13:32,False,812,13.533333
RN8yoi-e2yc,RN8yoi-e2yc,Mythical Kitchen,1.9M subscribers,$420 Pizza Hut Stuffed Crust Pizza | Fancy Fas...,1,https://www.youtube.com/watch?v=RN8yoi-e2yc,NaN,2.7M views,Food,"- Oh, that's dirty.\r\n- Wow! - Whoa.\r\n- You...",24:26,True,1466,24.433333
IugcIAAZJ2M,IugcIAAZJ2M,Munchies,4.59M subscribers,The Iconic $1 Pizza Slice of NYC | Street Food...,0,https://www.youtube.com/watch?v=IugcIAAZJ2M,2 years ago,11M views,Food,if you want good pizza come to st marks it's t...,7:51,False,471,7.850000

### 3 Продемонстрировать работу .groupby, на основе группировок в groupby вычисляете агрегатные функции по одной или нескольким колонкам. Какую информацию о данных вы получили, выполнив данную операцию? Запишите ответ в комментариях.

Время видео для каждой категории

In [49]:
top_categories = data[['Category', 'Seconds', 'Minutes']].groupby('Category').sum().sort_values(by="Category")
top_categories

                      Seconds      Minutes
Category
Automobile             154193  2569.883333
Automobile,Comedy       31243   520.716667
Blog                   152747  2545.783333
Blog,Comedy             52576   876.266667
Blog,Entertainment      27696   461.600000
Blog,Science            19842   330.700000
Comedy                   5434    90.566667
Comedy,Entertainment    37081   618.016667
Comedy,Informative      52864   881.066667
Entertainment           19830   330.500000
Entertainment,Blog      35452   590.866667
Entertainment,Comedy    28773   479.550000
Food                   225898  3764.966667
Food,Entertainment      39701   661.683333
Informative            156682  2611.366667
News                   130727  2178.783333
Science                299740  4995.666667
Tech                   140087  2334.783333
Tech,Comedy             18243   304.050000
Tech,Informative        18887   314.783333
Tech,News               15570   259.500000
VideoGames             214926  3582.100000

### 4 Решейпинг данных 1Dto2D с помощью .pivot (можно подать на вход результаты агрегатов, полученных ранее через .groupby (сгруппировать по двум полям), либо прекрасно заходит сюда данные из SQL сгруппированные предварительно по 2-м полям)

Долго думал как применить .pivot для результата .groupby выше, но не смог придумать что-то полезное. Пускай будет "вывод времени в минутах для категории только в той колонке секунд, которая соответствует категории"

In [51]:
top_categories.pivot(columns="Seconds", values='Minutes').fillna(0)

Seconds,5434,15570,18243,18887,19830,19842,27696,28773,31243,35452,...,52576,52864,130727,140087,152747,154193,156682,214926,225898,299740
Category,,,,,,,,,,,,,,,,,,,,,
Automobile,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2569.883333,0.000000,0.0,0.000000,0.000000
"Automobile,Comedy",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,520.716667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Blog,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2545.783333,0.000000,0.000000,0.0,0.000000,0.000000
"Blog,Comedy",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,876.266667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Blog,Entertainment",0.000000,0.0,0.00,0.000000,0.0,0.0,461.6,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Blog,Science",0.000000,0.0,0.00,0.000000,0.0,330.7,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Comedy,90.566667,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Comedy,Entertainment",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Comedy,Informative",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,881.066667,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Entertainment,0.000000,0.0,0.00,0.000000,330.5,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Entertainment,Blog",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,590.866667,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Entertainment,Comedy",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,479.55,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Food,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,3764.966667,0.000000
"Food,Entertainment",0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Informative,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2611.366667,0.0,0.000000,0.000000
News,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,2178.783333,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
Science,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,4995.666667
Tech,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,2334.783333,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Tech,Comedy",0.000000,0.0,304.05,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Tech,Informative",0.000000,0.0,0.00,314.783333,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
"Tech,News",0.000000,259.5,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
VideoGames,0.000000,0.0,0.00,0.000000,0.0,0.0,0.0,0.00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3582.1,0.000000,0.000000

### 5 Решейпинг 1Dto2D данных соединённый с группировкой / агрегацией (одним словом — сводная таблица): .pivot_table

Количество видео, созданных на канале, принадлежавших определённой категории
(Например, канал 3Blue1Brown создал 30 видео категории Science)

In [57]:
pd.pivot_table(data, values='Id', index='Category', columns='Channel', aggfunc="count").fillna(0)

Channel,3Blue1Brown,A&E,About To Eat,Abroad in Japan,Austin Evans,BBC News,Barely Sociable,Bon Appétit,Brooklyn Nine-Nine,BuzzFeedVideo,...,VICE,Veritasium,Vox,Vsauce,Web Dev Simplified,carwow,gameranx,jacksepticeye,penguinz0,videogamedunkey
Category,,,,,,,,,,,,,,,,,,,,,
Automobile,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0
"Automobile,Comedy",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Blog,0.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Blog,Comedy",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0
"Blog,Entertainment",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Blog,Science",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Comedy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Comedy,Entertainment",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Comedy,Informative",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Entertainment,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Entertainment,Blog",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Entertainment,Comedy",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Food,0.0,0.0,27.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Food,Entertainment",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Informative,0.0,0.0,0.0,0.0,0.0,0.0,28.0,0.0,0.0,0.0,...,0.0,0.0,28.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
News,0.0,30.0,0.0,0.0,0.0,26.0,0.0,0.0,0.0,0.0,...,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Science,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,30.0,0.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0
Tech,0.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,28.0,0.0,0.0,0.0,0.0,0.0
"Tech,Comedy",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Tech,Informative",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Tech,News",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VideoGames,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,25.0,30.0,0.0,30.0

### 6 Посчитать квантили распределения какого-либо вещественного признака (с помощью numpy.quantile или numpy.percentile)

In [58]:
 np.quantile(data['Seconds'].fillna(0), 0.5)

607.0


### 7 Посчитать гистограмму какого-либо вещественного признака (с помощью numpy.histogram). Значения гистограммы можете использовать как вариант в качестве загрубленного числового признака для заданий (4) или (5).

In [ ]:
np.hist


### 8 Получить DataFrame с MultiIndex любым способом: через конструктор (в документации увидите множество видов конструкторов для создания MultiIndex с нуля), через read_sql / read_csv / read_excel, read_*, через pivot_table, через groupby или иными способами.

### 9 Переставить местами уровни индекса

### 10 Транспонировать таблицу (или создать новую другую) с MultiIndex

### 11 Удалить один из уровней индекса или добавить новый уровень индекса (можно инициализированный константой)

### 12 Продемонстировать работу .merge


### 13 Продемонстрировать работу с .concat или append

### 14 Проитерировать dataframe построчно .iterrows(). Выполните что-то имеющее смысл внутри цикла